# Generated by Django 5.1.4 on 2025-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='memories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_at', models.DateTimeField()),
            ],
        ),
    ]
