# Generated by Django 5.1.4 on 2025-08-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-created_at']},
        ),
    ]
