# Generated by Django 6.0 on 2026-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcapp', '0002_alter_memory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='secret_key_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
